baseURL: 'http://hugo.wongssh.cf/'
languageCode: 'en-us'
title: "Wong's Blog"
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

minify:
  disableXML: true
  minifyOutput: true 

outputs:
    home:
        - HTML
        - RSS
        - JSON

params:
  env: production
  title: Wong's Blog
  description: A blog about python, JavaScript, front-end, web3 and back-end
  keywords: [python, javascript, front-end, back-end, web3, blockchain]
  author: WongSSH
  images: https://ae01.alicdn.com/kf/H60a2fb584e4a4e7f8a7c727d55647953Q.jpg
  DateFormat: "January 2, 2006"
  defaultTheme: auto
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true

  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: true
  tocopen: true

  homeInfoParams:
      Title: "WongSSH's Blog"
      Content: >
          - Welcome to my blog.

          - You can find web3, smart contract, golang, python and many other interesting contents
          
  socialIcons:
      - name: github
        url: "https://github.com/wangshouh"
      - name: Rss
        url: "index.xml"
      - name: Email
        url: "wongshouhao@outlook.com"